### PR TITLE
- Issue #8: Add artifactFilter to prevent inadvertently using the sou…

### PR DESCRIPTION
**Pull request by scottweaver**
- Issue #8: Add artifactFilter to prevent inadvertently using the source jar instead of the binary jar for aspectj weaver.
- Bump SBT version to 0.13.13
- Issue #8: Change settings in ping pong example to demonstrate and reproduce the source jar issue.

### CODE REVIEW

**Comment by dpsoft** [comment]
@scottweaver awesome!!! what about to update the `aspectj-weaver` version to the latest 1.8.9. WDYT?

**Comment by scottweaver** [comment]
Sure, I can do that.  I can also look at cleaning up some of the SBT deprecation warnings if you are cool with that?

**Comment by dpsoft** [comment]
@scottweaver yes please!.

**Comment by scottweaver** [comment]
@dpsoft

 That should be most of the compile warnings in AspectJRunner.  `Project` was moved to a build.sbt per deprecation on the `Build` trait.

**Comment by dpsoft** [comment]
@scottweaver awesome man!!! thanks for proposing this PR. I will make a new release at night.

**Pull request merged**
